// GENERATED by tools/build-web-config.mjs — do not edit by hand.
//
// The page once carried its own copy of the feed list and the two drifted, so three live
// feeds were missing from it. There is one list now, in prober/lib/config.mjs, and this
// file is derived from it. Run `node tools/build-web-config.mjs` after changing a feed.
window.LENS = {
  creditcoinRpc: 'https://rpc.cc3-testnet.creditcoin.network',
  explorer: 'https://creditcoin-testnet.blockscout.com',
  registry: '0x5c5bEE8b3D942cB7782071e13A272C7AE9f7C907',
  aggregator: '0x134dbefE46b803ADab301D3c85f33E82a16A3993',
  reserveMonitor: '0xB40692dD5077B4b2e5A75AccF4F610bac8b9C288',
  market: '0x4d983eD19F7b1dDae5b5B2D2C00dD481ea581DAe',
  votePort: '0xe43E5484Da58762800e7f495076658586295ccD0',
  snapshotProver: '0xc722549aCe290e165C76F32d76f5bab40dBe6Df8',
  breaker: '0x9ddC59f0F9b434B74A9ceB015Ee1c6861BbEc936',
  escrow: '0x4bab50d47E054E32C91F19E4E30027422061f636',

  // Source chains, keyed by native chain id. Chain keys are resolved at runtime from the
  // precompile and never written down: the same integer means a different chain on a
  // different Attestcoin environment.
  sources: {
    1: {
      label: "Ethereum mainnet",
      rpc: 'https://ethereum-rpc.publicnode.com',
      explorer: 'https://etherscan.io',
    },
    11155111: {
      label: "Ethereum Sepolia",
      rpc: 'https://ethereum-sepolia-rpc.publicnode.com',
      explorer: 'https://sepolia.etherscan.io',
    },
  },

  feeds: [
    {
      name: "sepolia.weth.totalSupply",
      note: "an ordinary ERC-20 read",
      chainId: 11155111,
      target: '0xfFf9976782d46CC05630D1f6eBAb18b2324d6B14',
      calldata: '0x18160ddd',
      decode: (hex) => `${(Number(BigInt(hex)) / 1e18).toLocaleString(undefined, { maximumFractionDigits: 3 })} WETH`,
    },
    {
      name: "sepolia.aave.wethBacking",
      note: "WETH actually held against the aWETH issued",
      chainId: 11155111,
      target: '0xC558DBdd856501FCd9aaF1E62eae57A9F0629a3c',
      calldata: '0x70a082310000000000000000000000005b071b590a59395fe4025a0ccc1fcc931aac1830',
      decode: (hex) => `${(Number(BigInt(hex)) / 1e18).toLocaleString(undefined, { maximumFractionDigits: 3 })} WETH`,
    },
    {
      name: "sepolia.aave.awethIssued",
      note: "the other leg of the solvency ratio",
      chainId: 11155111,
      target: '0x5b071b590a59395fE4025A0Ccc1FcC931AAc1830',
      calldata: '0x18160ddd',
      decode: (hex) => `${(Number(BigInt(hex)) / 1e18).toLocaleString(undefined, { maximumFractionDigits: 3 })} aWETH`,
    },
    {
      name: "sepolia.lvote.pastVotes",
      note: "historical state, with no storage proof anywhere",
      chainId: 11155111,
      target: '0x99E1749Fd45Bb14CF59139b04Cc387981f3ef66e',
      calldata: '0x3a46b1a8000000000000000000000000cf7a68bf1585c36f0cc0077ce16888f6388fc3590000000000000000000000000000000000000000000000000000000000b22c6e',
      decode: (hex) => `${(Number(BigInt(hex)) / 1e18).toLocaleString()} LVOTE`,
    },
    {
      name: "sepolia.chainlink.ethUsd",
      note: "a Chainlink feed carried onto a chain Chainlink does not serve",
      chainId: 11155111,
      target: '0x694AA1769357215DE4FAC081bf1f309aDC325306',
      calldata: '0x50d25bcd',
      decode: (hex) => `$${(Number(BigInt(hex)) / 1e8).toFixed(2)} per ETH`,
    },
    {
      name: "sepolia.aave.isPoolAdmin",
      note: "",
      chainId: 11155111,
      target: '0x7F2bE3b178deeFF716CD6Ff03Ef79A1dFf360ddD',
      calldata: '0x7be53ca1000000000000000000000000fa0e305e0f46ab04f00ae6b5f4560d61a2183e00',
      decode: (hex) => BigInt(hex) === 1n ? 'true (proven)' : 'false (proven)',
    },
    {
      name: "sepolia.aave.isPoolAdminStranger",
      note: "",
      chainId: 11155111,
      target: '0x7F2bE3b178deeFF716CD6Ff03Ef79A1dFf360ddD',
      calldata: '0x7be53ca1000000000000000000000000000000000000000000000000000000000000dead',
      decode: (hex) => BigInt(hex) === 1n ? 'true (proven)' : 'false (proven)',
    },
    {
      name: "mainnet.steth.rate",
      note: "a real Ethereum mainnet value, on a testnet deployment",
      chainId: 1,
      target: '0xae7ab96520DE3A18E5e111B5EaAb095312D7fE84',
      calldata: '0x7a28fb880000000000000000000000000000000000000000000000000de0b6b3a7640000',
      decode: (hex) => `${(Number(BigInt(hex)) / 1e18).toFixed(9)} ETH per share`,
    },
    {
      name: "mainnet.ens.pastSupply",
      note: "ENS answering about its own past, 1,000 blocks back",
      chainId: 1,
      target: '0xC18360217D8F7Ab5e7c516566761Ea12Ce7F9D72',
      calldata: '0x8e539e8c00000000000000000000000000000000000000000000000000000000018bf046',
      decode: (hex) => `${(Number(BigInt(hex)) / 1e18).toLocaleString()} ENS`,
    },
    {
      name: "mainnet.uniswap.ethUsdcTwap",
      note: "a 30-minute average — the class the lag was designed around",
      chainId: 1,
      target: '0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640',
      calldata: '0x883bdbfd0000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000000000000000000200000000000000000000000000000000000000000000000000000000000007080000000000000000000000000000000000000000000000000000000000000000',
      decode: (hex) => `$${(Number(BigInt(hex)) / 1e8).toFixed(2)} per ETH`,
    },
  ],
};
